import "./globals.css";
import type { Metadata } from "next";
import { Inter, Lora, Nunito, Quicksand, Raleway } from "next/font/google";
import { Providers } from "../features/provider";
import { NextAuthProvider } from "./session-provider";

const font = Quicksand({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={font.className}>
				<Providers>
					<NextAuthProvider>{children}</NextAuthProvider>
				</Providers>
			</body>
		</html>
	);
}
